### PR TITLE
connecting test2 to dhananjana

### PR DESCRIPTION
**Pull request by Sdhananjana1998**
hi,
I have committed test2 please review and approve
regards,

### CODE REVIEW

**Comment by tharindunadeeshan** [comment]
Hii
dhananjana your code looks good.please add one more check
Regards
Nadeeshan.

**Comment by Sdhananjana1998** [comment]
hi 
nadeeshan 
i have additional checks please approve.
regards
dhananjana.

**Comment by tharindunadeeshan** [comment]
hi dhananjana
your code looks good, please go ahead with merge  to master branch.
nadeeshan

**Comment by tharindunadeeshan** [comment]
Hii
Dhananjana your code looks good. please add one more check.
Regards
Nadeeshan

**Pull request merged**
